resources:
  schemas:
    tpch_schema:
      catalog_name: ${var.catalog}
      name: tpch_schema
      comment: |
        # Lakeflow Project Schema - Bronze
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY