resources:
  schemas:
    lakeflow_schema_bronze:
      catalog_name: ${var.catalog}
      name: ${var.schema}_bronze
      comment: |
        # Lakeflow Project Schema - Bronze
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY

    lakeflow_schema_silver:
      catalog_name: ${var.catalog}
      name: ${var.schema}_silver
      comment: |
        # Lakeflow Project Schema - Silver
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY

    lakeflow_schema_gold:
      catalog_name: ${var.catalog}
      name: ${var.schema}_gold
      comment: |
        # Lakeflow Project Schema - Gold
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY
            
    test_schema:
      catalog_name: ${var.catalog}
      name: test_schema
      comment: |
        # Lakeflow Project Schema - Gold
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY