resources:
  schemas:
    lakeflow_bronze:
      catalog_name: ${var.catalog}
      name: lakeflow_bronze
      comment: |
        # Lakeflow Project Schema - Bronze
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY
    lakeflow_silver:
      catalog_name: ${var.catalog}
      name: lakeflow_silver
      comment: |
        # Lakeflow Project Schema - Silver
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY
    lakeflow_gold:
      catalog_name: ${var.catalog}
      name: lakeflow_gold
      comment: |
        # Lakeflow Project Schema - Gold
        This schema is used for the **Lakeflow Pipelines Python** project.
      grants:
        - principal: ${workspace.current_user.userName}
          privileges:
            - MANAGE
            - SELECT
            - MODIFY