"""
Offline test for the PyDABs integration in resources/__init__.py.

Exercises the whole glue path against the committed dbt manifest (no Databricks workspace
required): reading the manifest, wiring the factory, generating notebook tasks, and registering
the job on a Resources object (which runs Job.from_dict, validating the task dict schema).
"""

import json
from importlib.metadata import version
from pathlib import Path

import pytest
import yaml
from databricks.bundles.core import Bundle

import resources
from databricks_dbt_factory.Utils import generate_task_key

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# The manifest is generated by `make manifest` (dbt parse). In a freshly initialized project it
# does not exist yet, so skip these tests rather than erroring until the user has run it.
pytestmark = pytest.mark.skipif(
    not (PROJECT_ROOT / resources.MANIFEST_PATH).exists(),
    reason="dbt manifest not found; run `make manifest` (dbt parse) first",
)


@pytest.fixture(autouse=True)
def _chdir_to_project_root(monkeypatch):
    # resources.MANIFEST_PATH is relative to the bundle root, as it is at deploy time.
    monkeypatch.chdir(PROJECT_ROOT)


def test_build_tasks_covers_every_buildable_node():
    # Every model/seed/snapshot node gets its own run task regardless of the BUNDLE_TESTS mode
    # (tests may be collapsed into per-resource `<resource>_test` tasks when bundling is on).
    tasks = resources._build_tasks("dev")
    task_keys = {task["task_key"] for task in tasks}

    manifest = json.loads((PROJECT_ROOT / resources.MANIFEST_PATH).read_text())
    buildable = [
        uid
        for uid, node in manifest.get("nodes", {}).items()
        if node.get("resource_type") in {"model", "seed", "snapshot"}
    ]
    expected_keys = {generate_task_key(uid) for uid in buildable}

    assert buildable, "committed manifest has no model/seed/snapshot nodes"
    assert expected_keys <= task_keys


def test_generated_tasks_are_serverless_notebook_tasks():
    tasks = resources._build_tasks("dev")

    for task in tasks:
        assert "notebook_task" in task, task
        assert task["environment_key"] == resources.ENVIRONMENT_KEY
        assert "job_cluster_key" not in task  # serverless only
        notebook_task = task["notebook_task"]
        assert notebook_task["notebook_path"] == resources.RUNNER_NOTEBOOK_PATH
        # The dbt target is injected into every command.
        assert "--target dev" in notebook_task["base_parameters"]["dbt_commands"]


def test_environment_pins_installed_dbt_databricks():
    # Single source of truth: the serverless env pins dbt-databricks to the exact
    # version installed in the bundle venv (the one used to generate the manifest).
    spec = resources._serverless_environment_spec()
    assert spec["dependencies"] == [f"dbt-databricks=={version('dbt-databricks')}"]

    # The generated job points its serverless environment at the synced env file.
    job = resources.build_job("dev")
    assert job.environments[0].spec.base_environment == resources.SERVERLESS_ENV_PATH


def test_load_resources_registers_the_job():
    result = resources.load_resources(Bundle(target="dev"))
    try:
        assert resources.JOB_NAME in result.jobs
        job = result.jobs[resources.JOB_NAME]
        assert job.environments[0].environment_key == resources.ENVIRONMENT_KEY

        # load_resources writes the base-environment file to the bundle root for
        # the bundle to sync; it pins dbt-databricks to the installed version.
        env_file = PROJECT_ROOT / resources.SERVERLESS_ENV_FILE
        assert env_file.exists()
        content = yaml.safe_load(env_file.read_text())
        pin = f"dbt-databricks=={version('dbt-databricks')}"
        assert content["dependencies"] == [pin]
    finally:
        (PROJECT_ROOT / resources.SERVERLESS_ENV_FILE).unlink(missing_ok=True)
