[format]
exclude = [
    # Templates are responsible for formatting at the source.
    "dbt_sql/*",
    "default_python/*",
    "default_sql/*",
    "mlops_stacks/*",
    "lakeflow_pipelines_python/*",
]
