resources:
  schemas:
    lakeflow_schema:
      catalog_name: ${var.catalog}
      name: ${var.schema}
      
      comment: |
        # Lakeflow Project Schema
        
        This schema is used for the **Lakeflow Pipelines Python** project.
        
        The schema contains tables and views managed by Delta Live Tables pipelines.
        
        **Created by**: ${workspace.current_user.displayName}
        
        ## Environment
        - **Catalog**: ${var.catalog}
        - **Schema**: ${var.schema}
        - **Target**: ${bundle.target}
      
      permissions:
        - user_name: ${workspace.current_user.userName}
          level: CAN_MANAGE
