.PHONY: init watch

init:
	databricks bundle generate dashboard --existing-path '/Workspace/Users/neelabh.kashyap@helen.fi/Helen Databricks Cost Dashboard.lvdash.json'

edit:
	databricks bundle generate dashboard --existing-path '/Workspace/Users/neelabh.kashyap@helen.fi/Helen Databricks Cost Dashboard.lvdash.json' --watch

