"""
Offline test for the PyDABs integration in resources/__init__.py.

Exercises the whole glue path against the committed dbt manifest (no Databricks workspace
required): reading the manifest, wiring the factory, generating notebook tasks, and registering
the job on a Resources object (which runs Job.from_dict, validating the task dict schema).
"""

import json
from pathlib import Path

import pytest
from databricks.bundles.core import Bundle

import resources

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# The manifest is generated by `make manifest` (dbt parse). In a freshly initialized project it
# does not exist yet, so skip these tests rather than erroring until the user has run it.
pytestmark = pytest.mark.skipif(
    not (PROJECT_ROOT / resources.MANIFEST_PATH).exists(),
    reason="dbt manifest not found; run `make manifest` (dbt parse) first",
)


@pytest.fixture(autouse=True)
def _chdir_to_project_root(monkeypatch):
    # resources.MANIFEST_PATH is relative to the bundle root, as it is at deploy time.
    monkeypatch.chdir(PROJECT_ROOT)


def test_build_tasks_covers_every_buildable_node():
    # Every model/seed/snapshot node gets its own task regardless of the BUNDLE_TESTS mode
    # (tests may be collapsed into per-resource `tests_*` tasks when bundling is on).
    tasks = resources._build_tasks("dev")
    task_keys = {task["task_key"] for task in tasks}

    manifest = json.loads((PROJECT_ROOT / resources.MANIFEST_PATH).read_text())
    buildable = {
        name
        for name, node in manifest.get("nodes", {}).items()
        if node.get("resource_type") in {"model", "seed", "snapshot"}
    }
    expected_keys = {name.replace(".", "_") for name in buildable}

    assert buildable, "committed manifest has no model/seed/snapshot nodes"
    assert expected_keys <= task_keys


def test_generated_tasks_are_serverless_notebook_tasks():
    tasks = resources._build_tasks("dev")

    for task in tasks:
        assert "notebook_task" in task, task
        assert task["environment_key"] == resources.ENVIRONMENT_KEY
        assert "job_cluster_key" not in task  # serverless only
        notebook_task = task["notebook_task"]
        assert notebook_task["notebook_path"] == resources.RUNNER_NOTEBOOK_PATH
        # The dbt target is injected into every command.
        assert "--target dev" in notebook_task["base_parameters"]["dbt_commands"]


def test_load_resources_registers_the_job():
    result = resources.load_resources(Bundle(target="dev"))

    assert resources.JOB_NAME in result.jobs
    job = result.jobs[resources.JOB_NAME]
    # Job.from_dict succeeded and the environment carries the dbt-databricks dependency.
    assert job.environments[0].environment_key == resources.ENVIRONMENT_KEY
